server:
  port: 8084
spring:
  application:
    name: Messaging-Service
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#  mail:
#    host: smtp.gmail.com
#    password:
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    username:

TWILIO_ACCOUNT_SID:
TWILIO_AUTH_TOKEN:
TWILIO_OUTGOING_SMS_NUMBER:

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka